name: Noir

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: v0.36.0

      - name: Run nargo test
        run: |
          nargo test
